version: 2

jobs:
  build:
    docker:
      - image: futtetennista/hakyll:4.9.8.0-ext
    environment:
      GH_EMAIL: deploy@tylerbenster.com
      GH_NAME: Circle-CI

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:89:f4:ba:52:92:72:20:8c:f4:4e:89:99:06:c1:36"
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "tylerbenster-com.cabal" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup --no-terminal
      - run: stack build --fast
      - run: make build
      - save_cache:
          name: Cache Dependencies
          key: haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "tylerbenster-com.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: deployment
          command: ./deploy.sh _site
