name: "Deploy"
on:
  pull_request:
  push:
jobs:
  benstercom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
    - name: Cache install Nix packages
      uses: nix-actions/cache-install@v1.0.6
      with:
        key: nix-${{ hashFiles('release.nix') }}
        nix_file: 'release.nix'
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Cache npm
      id: cache-node
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: add npm pkgs
      if: steps.cache-node.outputs.cache-hit != 'true'
      run: npm install tailwindcss @tailwindcss/typography && npm i -D postcss postcss-cli postcss-import autoprefixer
    - run: nix-shell --run "npx postcss static/css/entry.css -o static/master.css"
    - run: nix-build
    - name: build site
      run: ./result/bin/site build
    - name: commit
      run: ./commit_site.sh _site
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: site
        directory: site