
name: "Deploy"
on:
  pull_request:
  push:
jobs:
  benstercom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: tbenst
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: add haskell.nix cache
      run: sudo touch /nix/nix.conf && sudo echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=\nsubstituters = https://hydra.iohk.io" >> /nix/nix.conf
    - name: add npm pkgs
      run: nix-shell --run "npm install tailwindcss @tailwindcss/typography && npm i -D postcss postcss-cli postcss-import autoprefixer postcss-100vh-fix"
    - name: preprocess css
      run: nix-shell --run "npx postcss static/css/entry.css -o static/master.css"
    - name: build hakyll site exe
      run: nix-build -A tylerbenster-com.components.exes.site
    - name: build site
      run: ./result/bin/site build
    - name: commit
      run: ./commit_site.sh _site
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: site
        directory: site
