
name: "Deploy"
on:
  pull_request:
  push:
jobs:
  benstercom:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.11
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          allow-import-from-derivation = true
          auto-optimise-store = true
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org https://cache.iog.io https://cache.zw3rk.com https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=

    - uses: cachix/cachix-action@v12
      with:
        name: tbenst
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: add npm pkgs
      run: nix-shell --run "npm install tailwindcss @tailwindcss/typography && npm i -D postcss postcss-cli postcss-import autoprefixer postcss-100vh-fix @fullhuman/postcss-purgecss"
    - name: preprocess css
      run: nix-shell --run "npx postcss static/css/entry.css -o static/master.css"
    - name: build hakyll site exe
      run: nix-build -A tylerbenster-com.components.exes.site
    - name: build site
      run: ./result/bin/site build
    - name: commit
      run: ./commit_site.sh _site
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: site
        directory: site
